[Interface]
# The phone's internal VPN IP
Address = 10.8.0.2/24
DNS = 8.8.8.8, 1.1.1.1
PrivateKey = <Mobile's Private Key>

[Peer]
# The Server's Public Key
PublicKey = WO8NY0H+rZgm0yUBsLbfOO+wMW3wcFAI4G7/F6ZUXz8=

# The magic link: Your Server's Public IP and Port
Endpoint = 45.32.109.14:51820

# Route ALL mobile traffic through the VPN
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 20