[Interface]
Address = 10.8.0.1/24
ListenPort = 51820
PrivateKey = <Server's Private Key>

# Replace 'enp1s0' below with your actual primary network interface name!
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o enp1s0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o enp1s0 -j MASQUERADE

[Peer]
# Mobile Client Information
PublicKey = 35ESuZTsdznVFpxLL6spf1tQnDVhRfy2la/BfzEriFU=
AllowedIPs = 10.8.0.2/32